swagger: '2.0'
info:
    title: IRIS API
    version: '0.0.1'
host: localhost
schemes:
    - http
basePath: /v1
produces:
    - application/json

paths:
  /petitions:
    $ref: 'petition_public_path.yml#/petitions'
  /petitions/{contentId}:
    $ref: 'petition_public_path.yml#/petitions_contentId'
  /admin/petitions:
    $ref: 'petition_admin_path.yml#/petitions'
  /admin/petitions/{contentId}:
    $ref: 'petition_admin_path.yml#/petitions_contentId'
