swagger: '2.0'
info:
    title: IRIS API
    version: '0.0.1'
    description: |
        The IRIS API
host: localhost:8080
schemes:
    - http
basePath: /v1
produces:
    - application/json

tags:
  - name: petition-public
    description: Public Petiton API
  - name: petition-admin
    description: Administrative Petiton API

paths:
  /petitions:
    $ref: 'petition_public_path.yml#/petitions'
  /petitions/{contentId}:
    $ref: 'petition_public_path.yml#/petitions_contentId'
  /petitions/{contentId}/support:
    $ref: 'petition_public_path.yml#/petitions_contentId_support'
  /petitions/{contentId}/state/reject:
    $ref: 'petition_public_state_path.yml#/petitions_contentId_state_reject'
  /petitions/{contentId}/state/{transitionName}:
    $ref: 'petition_public_state_path.yml#/petitions_contentId_state_transitionName'
  /admin/petitions:
    $ref: 'petition_admin_path.yml#/petitions'
  /admin/petitions/{contentId}:
    $ref: 'petition_admin_path.yml#/petitions_contentId'
