swagger: '2.0'
info:
    title: IRIS API
    version: '0.0.1'
    description: |
        The IRIS API
schemes:
    - http
basePath: /v1

consumes:
    - application/json
produces:
    - application/json

tags:
  - name: petition
    description: Public Petiton API
  - name: petition_event
    description: Petiton Event API
  - name: auth
    description: Authentication API
  - name: petition_admin
    description: Administrative Petiton API
  - name: user_admin
    description: Administrative User API
  - name: Options
    description: The `OPTIONS` endpoints

paths:
  /petitions:
    $ref: 'petition_public_path.yml#/petitions'
  /petitions/{contentId}:
    $ref: 'petition_public_path.yml#/petitions_contentId'
  /petitions/{contentId}/support:
    $ref: 'petition_public_path.yml#/petitions_contentId_support'

  /petitions/{contentId}/event/reject:
    $ref: 'petition_public_event_path.yml#/petitions_contentId_event_reject'
  /petitions/{contentId}/event/publish:
    $ref: 'petition_public_event_path.yml#/petitions_contentId_event_publish'
  /petitions/{contentId}/event/delete:
    $ref: 'petition_public_event_path.yml#/petitions_contentId_event_delete'
  /petitions/{contentId}/event/close:
    $ref: 'petition_public_event_path.yml#/petitions_contentId_event_close'
  /petitions/{contentId}/event/approved:
    $ref: 'petition_public_event_path.yml#/petitions_contentId_event_approved'
  /petitions/{contentId}/event/sendLetter:
    $ref: 'petition_public_event_path.yml#/petitions_contentId_event_sendLetter'
  /petitions/{contentId}/event/setFeedback:
    $ref: 'petition_public_event_path.yml#/petitions_contentId_event_setFeedback'
  /petitions/{contentId}/event/{transitionName}:
    $ref: 'petition_public_event_path.yml#/petitions_contentId_event_transitionName'

  /auth/whoami:
    $ref: 'auth_path.yml#/auth_whoami'
  /auth/ssologin:
    $ref: 'auth_path.yml#/auth_ssologin'
  /auth/ssotoken:
    $ref: 'auth_path.yml#/auth_ssotoken'
  /auth/logout:
    $ref: 'auth_path.yml#/auth_logout'

  /admin/petitions:
    $ref: 'petition_admin_path.yml#/petitions'
  /admin/petitions/{contentId}:
    $ref: 'petition_admin_path.yml#/petitions_contentId'

  /admin/users:
    $ref: 'user_admin_path.yml#/users'
  /admin/users/{contentId}:
    $ref: 'user_admin_path.yml#/users_contentId'

