swagger: '2.0'
info:
    title: IRIS API
    version: '0.0.1'
    description: |
        The IRIS API
basePath: /v1

consumes:
    - application/json
produces:
    - application/json

tags:
  - name: petition
    description: Public Petiton API
  - name: petition_event
    description: Petiton Event API
  - name: auth
    description: Authentication API
  - name: petition_admin
    description: Administrative Petiton API
  - name: user_admin
    description: Administrative User API
  - name: city
    description: City Public API
  - name: city_import
    description: City Importer API
  - name: city_admin
    description: Administrative City API
  - name: weblocation_admin
    description: Administrative WebLocation API
  - name: supporter_admin
    description: Administrative Supporter API
  - name: og
    description: Open Graph
  - name: statemachine
    description: Statemachine API
  - name: Options
    description: The `OPTIONS` endpoints

paths:
  /petitions:
    $ref: 'petition_public_path.yml#/petitions'
  /petitions/{contentId}:
    $ref: 'petition_public_path.yml#/petitions_contentId'
  /token/{token}/petitions:
    $ref: 'petition_public_path.yml#/petitions_by_token'

  /petitions/{contentId}/event/reject:
    $ref: 'petition_public_event_path.yml#/petitions_contentId_event_reject'
  /petitions/{contentId}/event/publish:
    $ref: 'petition_public_event_path.yml#/petitions_contentId_event_publish'
  /petitions/{contentId}/event/delete:
    $ref: 'petition_public_event_path.yml#/petitions_contentId_event_delete'
  /petitions/{contentId}/event/support:
    $ref: 'petition_public_event_path.yml#/petitions_contentId_event_support'
  /petitions/{contentId}/event/close:
    $ref: 'petition_public_event_path.yml#/petitions_contentId_event_close'
  /petitions/{contentId}/event/approved:
    $ref: 'petition_public_event_path.yml#/petitions_contentId_event_approved'
  /petitions/{contentId}/event/letterSent:
    $ref: 'petition_public_event_path.yml#/petitions_contentId_event_letterSent'
  /petitions/{contentId}/event/setFeedback:
    $ref: 'petition_public_event_path.yml#/petitions_contentId_event_setFeedback'
  /petitions/{contentId}/event/check:
    $ref: 'petition_public_event_path.yml#/petitions_contentId_event_check'
  /petitions/{contentId}/event/tick:
    $ref: 'petition_public_event_path.yml#/petitions_contentId_event_tick'
  /petitions/{contentId}/event/force_state:
    $ref: 'petition_public_event_path.yml#/petitions_contentId_event_force_state'
  /petitions/{contentId}/event/{transitionName}:
    $ref: 'petition_public_event_path.yml#/petitions_contentId_event_transitionName'

  /auth/whoami:
    $ref: 'auth_path.yml#/auth_whoami'
  /auth/ssologin:
    $ref: 'auth_path.yml#/auth_ssologin'
  /auth/ssotoken:
    $ref: 'auth_path.yml#/auth_ssotoken'
  /auth/logout:
    $ref: 'auth_path.yml#/auth_logout'

  /admin/petitions:
    $ref: 'petition_admin_path.yml#/petitions'
  /admin/petitions/{contentId}:
    $ref: 'petition_admin_path.yml#/petitions_contentId'

  /cities:
    $ref: 'city_public_path.yml#/cities_search'
  /cities/{contentId}:
    $ref: 'city_public_path.yml#/cities_contentId'
  /import/cities:
    $ref: 'city_public_path.yml#/import_cities'

  /admin/cities:
    $ref: 'city_admin_path.yml#/cities'
  /admin/cities/{contentId}:
    $ref: 'city_admin_path.yml#/cities_contentId'

  /admin/weblocations:
    $ref: 'weblocation_admin_path.yml#/weblocations'
  /admin/weblocations/{contentId}:
    $ref: 'weblocation_admin_path.yml#/weblocations_contentId'
  /admin/weblocations/{contentId}/resetog:
    $ref: 'weblocation_admin_path.yml#/weblocations_contentId_resetog'

  /admin/users:
    $ref: 'user_admin_path.yml#/users'
  /admin/users/{contentId}:
    $ref: 'user_admin_path.yml#/users_contentId'

  /admin/supporters:
    $ref: 'supporter_admin_path.yml#/supporters'

  /og/check:
    $ref: 'og_path.yml#/og_check'

  /admin/statemachine/{name}:
    $ref: 'statemachine_path.yml#/statemachine_name'
